In [1]:
import numpy as np

In [2]:
data = np.random.rand(2,3)

In [3]:
data

array([[0.57583381, 0.17902492, 0.00400552],
       [0.64524796, 0.40190772, 0.67526822]])

In [4]:
data * 10

array([[5.75833814, 1.79024922, 0.04005523],
       [6.45247958, 4.01907722, 6.75268216]])

In [5]:
data.shape

(2, 3)

In [6]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1,2,3,4], [5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

arr2.shape

(2, 4)

In [9]:
np.empty((2,3,4))

array([[[-2.00000000e+000, -2.00000000e+000,  6.42285340e-323,
          0.00000000e+000],
        [ 2.12199579e-314,  5.30276956e+180,  3.31033942e-033,
          4.57134226e-071],
        [ 5.06636307e-086,  3.36010586e-143,  6.01433264e+175,
          6.93885958e+218]],

       [[ 5.56218858e+180,  3.94356143e+180,  5.40129574e-038,
          8.23592039e-067],
        [ 1.54469009e+185,  5.98653548e+174,  5.42986599e-143,
          1.50008929e+248],
        [ 1.83672936e+118,  2.68615006e+122, -2.00000000e+000,
          1.49457436e-154]]])

In [18]:
2**4


16

In [21]:
arr = np.arange(10)


arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [24]:
arr_slice[1] = 12345

In [25]:
arr_slice


array([    5, 12345,     7])

In [26]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [27]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])