In [71]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt


In [9]:
obj = pd.Series([4, 7, -5, 3, 9])
obj


0    4
1    7
2   -5
3    3
4    9
dtype: int64

In [10]:
obj.values



array([ 4,  7, -5,  3,  9])

In [11]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2


d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [22]:
obj2['a']

a   -5
dtype: int64

In [18]:
obj2['d'] = 6

In [24]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [27]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [28]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [29]:
'b' in obj2

True

In [30]:
'e' in obj2

False

In [31]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}


In [32]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
pd.isnull(obj4)


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [35]:
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [36]:
obj4.isnull()


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [37]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [42]:

obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan','John']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
John     9
dtype: int64

In [26]:

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame.items

<bound method DataFrame.iteritems of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9>

In [28]:
DataFrame(data, columns=['year', 'state', 'pop']).items


<bound method DataFrame.iteritems of    year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9>

In [31]:

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five'])
frame2.items

<bound method DataFrame.iteritems of        year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN>

In [32]:
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [33]:

frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [37]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [39]:
frame2['debt'] = 16.5
frame2.items

<bound method DataFrame.iteritems of        year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5>

In [41]:
frame2['debt'] = np.arange(5.)
# frame2['debt'] = np.arange(6.)
frame2.items

<bound method DataFrame.iteritems of        year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0>

In [76]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
# 없는 값은 NaN으로 덮어씌워짐
frame2['debt'] = val
frame2.items

<bound method DataFrame.iteritems of        year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7>

In [78]:

frame2['eastern'] = frame2.state == 'Ohio'
frame2.items
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False]], dtype=object)

In [75]:

del frame2['eastern']
frame2.items


KeyError: 'eastern'

In [74]:

pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3.items
frame3.values


array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [61]:
print(frame3.T)

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6


In [62]:
print(DataFrame(pop, index=[2001, 2002, 2003]))

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN


In [58]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [59]:
index[1:]


Index(['b', 'c'], dtype='object')

In [64]:
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

In [67]:
frame3.items


<bound method DataFrame.iteritems of       Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6>

In [68]:
'Ohio' in frame3.columns
2003 in frame3.index

False